### ISSUE TITLE
Can't install NetCDF4 1.5.8 for Python 3.9.13 on M1 MacOS 12.4

### ISSUE THREAD

**Issue by AllanLeanderRostockHansen** [MacPython/netcdf4-python-wheels#21]
Hi

I'm in dire need of a wheel able to install NetCDF4 1.5.8 for Python 3.9.13 on M1 MacOS 12.4.
Is it possible to trigger a build and release for this version of MacOS?

Best regards
Allan

**Comment by danieltomasz** [comment]
I was able to install but I am getting  this error on impotrt netCDF4 `symbol not found in flat namespace '_H5get_libversion'` both in 3.9.13 and 3.10.5

**Comment by danieltomasz** [comment]
@AllanLeanderRostockHansen 
Maybe this will help?  Those wheels work for me https://github.com/MacPython/netcdf4-python-wheels/releases/tag/v1.5.8rel

**Comment by AllanLeanderRostockHansen** [comment]
That is the exact same error I get, and you're right, I can install but not import netCDF4 when installing it from Poetry (`netCDF4 = "^1.5.8"`).
The wheels provided with this repository doesn't even install though, and my initial though is that it's due to my MacBook running MacOS Monterey (12.4) rather than MacOS 11, which is what the wheels appears to be build for?

This is the error I get:
```
  • Installing netcdf4 (1.5.8 /Users/allanlrh/src/sca-path-finder/wheelhouse/netCDF4-1.5.8-cp310-cp310-macosx_11_0_arm64.whl): Failed

  EnvCommandError

  Command ['/Users/allanlrh/src/sca-path-finder/.direnv/python-3.9.13/bin/pip', 'install', '--no-deps', '/Users/allanlrh/src/sca-path-finder/wheelhouse/netCDF4-1.5.8-cp310-cp310-macosx_11_0_arm64.whl'] errored with the following return code 1, and output:
  ERROR: netCDF4-1.5.8-cp310-cp310-macosx_11_0_arm64.whl is not a supported wheel on this platform.
```

What version of MacOS are you running? And are you using a M1 or M2 based computer or one using an Intel CPU?

**Comment by AllanLeanderRostockHansen** [comment]
Sorry, I just realized that I was using the Python 3.10 wheel on Python 3.9. Changing to `netCDF4-1.5.8-cp39-cp39-macosx_10_9_universal2.whl` fixes the problem.
