### ISSUE TITLE
python 3.11 and 3.12 builds failing on macosx and linux

### ISSUE THREAD

**Issue by jswhit** [MacPython/netcdf4-python-wheels#23]
For macosx see:  https://github.com/MacPython/netcdf4-python-wheels/actions/runs/6582260301
For linux see: https://github.com/MacPython/netcdf4-python-wheels/actions/runs/6582260298

@matthew-brett if you have time could you take a look?  I'm stumped.

**Comment by matthew-brett** [comment]
Hi - sorry - term-time proving exhausting.   Do you have the latest commit of multibuild from https://github.com/multi-build/multibuild ?   That should cover those later versions.   I think the latest commit is 452dd2d .

**Comment by mattip** [comment]
I see [multibuild @ b89bb90](https://github.com/multi-build/multibuild/tree/b89bb903e94308be79abefa4f436bf123ebb1313) which is from [Oct 2021](https://github.com/multi-build/multibuild/commit/b89bb90). To get the latest try
```
git checkout -b update-multibuild
cd multibuild
git checkout devel
git pull
git commit ...
git push ...
```

**Comment by jswhit** [comment]
Thanks @matthew-brett - that should have been the first thing to try (and indeed I mistakenly thought I had updated multibuild).  All builds now working.
