### ISSUE TITLE
builds for v1.4.0rel are failing

### ISSUE THREAD

**Issue by jswhit** [MacPython/netcdf4-python-wheels#3]
see https://travis-ci.org/search/netcdf4-python-wheels

not obvious to me what the problem is.

**Comment by jswhit** [comment]
@matthew-brett, I'd appreciate it if you could take a look at this - it's blocking the release of 1.4.0.

**Comment by matthew-brett** [comment]
Probably needs latest multibuild to sort out various changes in pip and the manylinux docker image.  I've updated and pushed, let's see if they build right.

**Comment by matthew-brett** [comment]
Mostly fixed, but test errors testing Python 3.5 / numpy 1.9.3 . 32-bit OSX failures, but at this stage it would be reasonable to drop those:

https://travis-ci.org/MacPython/netcdf4-python-wheels/builds/375850802

**Comment by matthew-brett** [comment]
Now hitting Travis-CI breakage : https://www.traviscistatus.com/incidents/0ch1w22m3lwc

**Comment by matthew-brett** [comment]
OK - rebuild is working now - can you branch the master branch to make a new release branch?

**Comment by matthew-brett** [comment]
@jswhit - sorry - I'm confused - are the builds OK now?   If not, what is the new error?

**Comment by jswhit** [comment]
Looks good now - thanks @matthew-brett !
